### ISSUE TITLE
初回インストール時に File Not Found が発生して先に進めない

### ISSUE THREAD

**Issue by i12o** [kodiful/plugin.audio.netradio#2]
Raspberry PI に libreelec 12.0 (kodi 21.0) をインストールした状態に、初めてこちらのアドオンをインストールしてみました(8.2.5)

何回か kodi 全体のリスタートなどしてもみましたが、

  .kodi/userdata/addon_data/plugin.audio.netradio/auth.json

が自動では生成されないため、毎回該当ファイルが読み込めないエラーが発生します。

python3 単体起動し、resources/lib/authenticate.py 単体で読み込み、Authenticate オブジェクトを作成して結果作成された auth.response を JSON に書き出し、それを auth.json として保存してから再度起動したところ、ラジオ局のリストが出るところまで到達しました。

が、そこから選局しようとしたところで、

  .kodi/userdata/addon_data/plugin.audio.netradio/timetable/timetable/

下のファイルが読み込めないというエラーが出て、選局に失敗します。

初回インストールで auth.json や timetable/〜/*.json といったファイルがまるで存在していない状況では、Exception が発生してしまい動作が停止してしまうのではないか、という気がします(確信はないです)。

Kodi が 21.0 なせいかもしれませんが、初回インストールから正常に動作するようになるまでの段取りなどが別途あるようであれば、ご教示頂けると幸いです。

```
2024-09-01 01:44:37.670 T:2213    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/plugin.audio.netradio/timetable/timetable/radk/BAYFM78.json'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.netradio/default.py", line 40, in <module>
                                                       Directory().show(path)
                                                     File "/storage/.kodi/addons/plugin.audio.netradio/resources/lib/directory.py", line 48, in show
                                                       self._add_station(path, item)
                                                     File "/storage/.kodi/addons/plugin.audio.netradio/resources/lib/directory.py", line 115, in _add_station
                                                       li = xbmcgui.ListItem(self._title(data))
                                                                             ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.netradio/resources/lib/directory.py", line 192, in _title
                                                       progs = self.read_as_json(os.path.join(self.TIMETABLE_PATH, data['type'], f'%s.json' % data['station']))
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.netradio/resources/lib/common.py", line 141, in read_as_json
                                                       return json.loads(Common.read(path))
                                                                         ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.netradio/resources/lib/common.py", line 136, in read
                                                       with open(path, 'rb') as f:
                                                            ^^^^^^^^^^^^^^^^
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/plugin.audio.netradio/timetable/timetable/radk/BAYFM78.json'
                                                   -->End of Python script error report<--
                                                   
```

**Comment by kodiful** [comment]
ご指摘ありがとうございます。
前回のアップデートの影響で初回起動時に必要なファイルがuserdataにコピーされない状況でした。
修正してバージョン8.2.6としました。
HPのダウンロードのリンクも修正しました。

**Comment by i12o** [comment]
ありがとうございます。
github から 8.2.6 の zip をダウンロード、インストールして無事に NHK ラジオが再生できるところまで確認できました。
radiko の局を選択すると止まってしまい、その後動作がおかしくなってしまうのですが、それはこちらの OS とかハードウェアの関係かもしれません。

とりあえず、初回インストールの問題に関しては解決したようですので、こちらの issue は close しておきます。
